#!/usr/bin/env bash
# Configures Ubuntu server to localhost 127.0.0.2 and facebook.com 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/^127\.0\.0\.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

 if ! grep -q'^127\.0\.0\.0\s*localhost' /etc/hosts; then
    echo '127.0.0.2 localhost' | sudo tee -a /etc/hosts

sudo sed -i '/facebook.com/d' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts